version: "3.3"  # Usamos una versión más antigua compatible con docker-compose 1.25.0

services:
  product-page:
    build:
      context: .
      dockerfile: dockerfile.product-page
    image: productpage/44
    container_name: productpage-44
    ports:
      - "9080:9080"
    environment:
      GROUP_NUM: "44"

  details:
    build:
      context: .
      dockerfile: dockerfile.details
    image: details/44
    container_name: details-44
    ports:
      - "9081:9080"
    environment:
      SERVICE_VERSION: v1
      ENABLE_EXTERNAL_BOOK_SERVICE: "true"

  reviews:
    image: reviews/44:v1  
    container_name: reviews-44
    ports:
      - "9082:9080"
    environment:
      ENABLE_RATINGS: "true" 
      SERVICE_VERSION: v1  
      STAR_COLOR: "red"

  ratings:
    build:
      context: .
      dockerfile: dockerfile.ratings
    image: ratings/44
    container_name: ratings-44      
    ports:
      - "9083:9080"
    environment:
      SERVICE_VERSION: v1
